### ISSUE TITLE
Training Code available?

### ISSUE THREAD

**Issue by vgoklani** [fattorib/Little-GPT#2]
Hey there,

Thanks for sharing your work!

I'd like to reproduce some of your results. 

I can't find your preprocessing code, are you planning to release that? 

I plan to start by running your main.py file. Anything I should be aware of? 

Thanks!

**Comment by fattorib** [comment]
Hey, thanks for the interest. I don't have the preprocessing code, but there are plenty of options to work with streaming text data. The NanoGPT dataset/dataloader [here](https://github.com/karpathy/nanoGPT/tree/master/data/openwebtext) should be good.  

The training code is all contained within ```main.py``` and the distributed training is handled with HuggingFace's [Accelerate](https://huggingface.co/docs/accelerate/index). This was done with an older version of the package that didn't support more advanced features such as ZeRO, FSDP, etc. Depending on your setup, updating to a newer version of Accelerate could provide you with increased training speed/decreased memory requirements.
